# Aljabar Matriks


1.  penjelasan tentang matriks
2.  operasi matriks
  *   penjumlahan
  *   perkalian
  *   pengurangan
  *   transpose matriks
3. membuat matrik A dan B dengan ordi 3x3 dan matriks C dengan ordo 3x2
4. tugas: buat program untuk mengalikan matriks A dan B tidak menggunakan '@'







  

A. Matriks

Matriks adalah suatu susunan bilangan real atau bilangan kompleks (atau elemen-elemen) yang disusun dalam baris dan kolom sehingga membentuk jajaran persegi panjang. contoh:

In [ ]:
import numpy as np
import numpy as sy
a=np.array([[1,2,3],[3,4,3],[5,5,6]])
print(a)

[[1 2 3]
 [3 4 3]
 [5 5 6]]


\begin{equation*}
A=
\begin{bmatrix}
1&2&3\\
3&4&3\\5&5&6
\end{bmatrix}
\end{equation*}

####Jenis-jenis Matriks


####1. Matriks Identitas
 Matriks persegi yang memiliki nilai 1 di diagonal utamanya dan nilai 0 di seluruh elemen lainnya. contoh Matriks Identitas:

In [ ]:
import numpy as np
import sympy as sy
A= np.eye(4)
A


\begin{equation*}
A=
\begin{bmatrix}
1&0&0&0\\
0&1&0&0\\
0&0&1&0\\
0&0&0&1
\end{bmatrix}
\end{equation*}

In [ ]:
import numpy as np

# Membuat matriks identitas 4x4
A = np.eye(4)

# Mengisi matriks dengan angka yang diinginkan
A = np.array([[2,3,4,7],[4,5,6,7],[2,4,5,6],[5,6,7,8]])

print("Matriks dengan angka yang dimasukkan:")
print(A)


*  Kode Python dibawah sama saja

In [ ]:
import numpy as np
import numpy as sy
#A= np.eye(4)
a=np.array([[2,3,4,7],[4,5,6,7],[2,4,5,6],[5,6,7,8]])
a


\begin{equation*}
A=
\begin{bmatrix}
2&3&4&7\\
4&5&6&7\\
2&4&5&6\\
5&6&7&8
\end{bmatrix}
\end{equation*}

####2. Matriks Nol
Matriks nol adalah matriks yang semua entrinya adalah bilangan nol.
contoh Matriks Nol:


In [ ]:
import numpy as np

# Tentukan ukuran matriks nol
baris = 3
kolom = 3

# Buat matriks nol menggunakan np.zeros
matriks_nol = np.zeros((baris, kolom))

print("Matriks Nol:")
print(matriks_nol)



\begin{equation*}
MatriksNol=
\begin{bmatrix}
0&0&0\\
0&0&0\\
0&0&0
\end{bmatrix}
\end{equation*}

####3.Matriks Baris
Matriks baris merupakan matriks yang terdiri atas satu baris saja. Contoh matriks Baris:


In [ ]:
import numpy as np

# Elemen-elemen matriks baris
baris = [1, 2, 3, 4]

# Buat matriks baris menggunakan np.array
matriks_baris = np.array([baris])

print("Matriks Baris:")
print(matriks_baris)


*  Kode Pyhton dibawah ini sama saja dengan yang di atas

In [ ]:
import numpy as np
import numpy as sy
a=np.array([[2,3,4,5]])
print('a=\n',a)

\begin{equation*}
A=
\begin{bmatrix}
2&3&4&5\\
\end{bmatrix}
\end{equation*}

####4. Matriks Kolom
Matriks baris merupakan matriks yang terdiri atas satu baris saja. Contoh Matriks Kolom:


!NOTE: '.reshape(-1, 1)',  tanda -1 digunakan untuk menandakan bahwa jumlah baris dalam matriks akan disesuaikan secara otomatis berdasarkan jumlah elemen yang ada, sedangkan 1 menunjukkan bahwa kita ingin memiliki hanya satu kolom dalam matriks tersebut.

In [ ]:
import numpy as np

# Elemen-elemen matriks kolom
kolom = [1, 2, 3, 4]

# Buat matriks kolom menggunakan np.array dan ubah dimensinya
matriks_kolom = np.array(kolom).reshape(-1, 1)

print("Matriks Kolom:")
print(matriks_kolom)


\begin{equation*}
A=
\begin{bmatrix}
1\\
2\\
3\\
4
\end{bmatrix}
\end{equation*}

####5. Matriks Diagonal
Matriks diagonal adalah matriks persegi yang elemen-elemen selain diagonal utamanya bernilai nol. Contoh dari Matriks Diagonal:



In [ ]:
import numpy as np

# Membuat matriks diagonal dengan elemen diagonal 1, 2, 3, 4
diagonal = [1, 2, 3, 4]
matriks_diagonal = np.diag(diagonal)

print("Matriks Diagonal:")
print(matriks_diagonal)


\begin{equation*}
MatriksDiagonal=
\begin{bmatrix}
1&0&0&0\\
0&2&0&0\\
0&0&3&0\\
0&0&0&4
\end{bmatrix}
\end{equation*}

####6. Matriks Simetris
Matriks simetris adalah matriks di mana elemen-elemennya simetris terhadap diagonal utamanya.
atau bisa dikatakan kolom menjadi baris. Contoh dari Matriks Simetris:


In [ ]:
import numpy as np

# Membuat matriks simetris secara manual
matriks_simetris = np.array([[1, 2, 3],
                             [2, 4, 5],
                             [3, 5, 6]])

print("Matriks Simetris:")
print(matriks_simetris)


*  sama saja seperti yang diatas

In [ ]:
import numpy as np
import numpy as sy
a=np.array([[1,2,3],[2,3,4],[4,5,4]])
a

\begin{equation*}
a=
\begin{bmatrix}
1&2&3\\
2&3&4\\4&5&4
\end{bmatrix}
\end{equation*}

####7. Matriks Segitiga Atas
Suatu matriks segitiga dikatakan matriks segitiga atas jika semua elemen di bawah diagonal utamanya adalah nol. Contoh dari Matriks Segitiga Atas:

In [ ]:
import numpy as np
import numpy as sy
a=np.array([[1,2,3],[0,4,5],[0,0,6]])
print("matriks segitiga atas: ")
print(a)

\begin{equation*}
A=
\begin{bmatrix}
1&2&3\\
0&4&5\\0&0&6
\end{bmatrix}
\end{equation*}

####8. Matriks Segitiga Bawah
 Suatu matriks segitiga dikatakan matriks segitiga bawah jika semua elemen di atas diagonal utamanya adalah nol. Contoh dari Segitiga Bawah:

In [ ]:
import numpy as np
import numpy as sy
a= np.array([[1,0,0],[4,5,0],[7,8,9]])
print("Matriks Segitiga Bawah: ")
print(a)

\begin{equation*}
A=
\begin{bmatrix}
1&0&0\\
4&5&0\\7&8&9
\end{bmatrix}
\end{equation*}

####9. Matriks Singular
matriks yang memiliki determinan nol.


####10. Matriks Persegi
matriks persegi adalah matriks yang memiliki jumlah baris dan jumlah kolom yang sama.

In [ ]:
import numpy as np
import numpy as sy
a= np.array([[3,4,5],[6,7,5],[7,6,5]])
print("Matriks Persegi: ")
print(a)

\begin{equation*}
A=
\begin{bmatrix}
3&4&5\\
6&7&5\\7&6&5
\end{bmatrix}
\end{equation*}

B. OPERASI PADA MATRIKS

In [ ]:
#A dan B= 3X3
#C = 3X2

import numpy as np
import sympy as sy
a=np.array ([[1, 0, 2],[2, 0, 4],[4, 6, 8]])
b=np.array ([[2, 3, 4],[4, 5, 6], [1, 2, 4]])
c=np.array ([[2, 3],[4, 5],[6, 7]])

print('A=\n',a)
print('B=\n',b)
print('C=\n',c)



\begin{align*}
A=
\begin{bmatrix}
1&0&2\\
2&0&4\\
4&6&8
\end{bmatrix}
&&
B=
\begin{bmatrix}
2&3&4\\
4&5&6\\1&2&4
\end{bmatrix}
&&
C=
\begin{bmatrix}
2&3\\
4&5\\
6&7
\end{bmatrix}
\end{align*}


##1. Penjumlahan Matriks
Penjumlahan matriks adalah operasi penjumlahan dua matriks dengan menjumlahkan komponen-komponennya yang seletak. Dua matriks dapat dijumlahkan jika jumlah baris dan kolomnya sama. Matriks hasil penjumlahannya juga akan memiliki ordo yang sama.


In [ ]:
print('A+B=\n',a+b)
print('B+A=\n',b+a)
print('sifat di atas merupakan sifat komunitatif karena A+B = B+A')

\begin{align*}
A+B=
\begin{bmatrix}
3&3&6\\
6&5&10\\
5&8&12
\end{bmatrix}
&&
B+A=
\begin{bmatrix}
3&3&6\\
6&5&10\\
5&8&12
\end{bmatrix}
\end{align*}


sifat di atas merupakan sifat komutatif karena A+B = B+A

##2. Pengurangan Matriks
Penguragan matriks memiliki konsep yang sama dengan penjumlahan. Dua buah matriks dapat dikurangkan apabila keduanya memiliki ordo yang sama.


In [ ]:
print('A-B=\n',a-b)
print('B-A=\n',b-a)
print('sifat di atas merupakan sifat komutatif karena A-B = B-A')

\begin{align*}
A-B=
\begin{bmatrix}
-1&-3&-2\\
-2&-5&-2\\
3&4&4
\end{bmatrix}
&&
B-A=
\begin{bmatrix}
1&3&2\\
2&5&2\\
-3&-4&-4
\end{bmatrix}
\end{align*}

sifat di atas merupakan sifat komutatif karena A-B = B-A


##3. Perkalian Matriks
Perkalian matriks sendiri adalah proses mengalikan setiap elemen baris pada matriks pertama dengan elemen kolom pada matriks kedua. Hasilnya kemudian dijumlahkan untuk memperoleh hasil akhir perkalian matriks.

In [ ]:
print('AB=\n',a@b)
print('AC=\n',a@c)
print('BC=\n',b@c)

\begin{align*}
AB=
\begin{bmatrix}
4&7&12\\
8&14&24\\
40&58&84
\end{bmatrix}
&&
AC=
\begin{bmatrix}
14&17\\
28&34\\
80&98
\end{bmatrix}
&&
BC=
\begin{bmatrix}
40&49\\
64&79\\
34&41
\end{bmatrix}
\end{align*}


*  Sifat Asosiasi:

 (AB)C = A(BC)



In [ ]:
print('A(BC) =\n', a@(b@c))
print('(AB)C =\n',(a@b)@c)


\begin{equation*}
A(BC)=
\begin{bmatrix}
108&131\\
216&262\\816&998
\end{bmatrix}
(AB)C=
\begin{bmatrix}
108&131\\
216&262\\
816&998
\end{bmatrix}
\end{equation*}

*  perkalian skalar

  c(AB) = (cA)B = A(cB)

In [ ]:
c = 3
print('c(AB)\n',c*(a@b))
print('(cA)B\n',(c*a)@b)
print('A(cB)\n',a@(c*b))

\begin{equation*}
c(AB)=
\begin{bmatrix}
12&21&36\\
24&42&72\\120&174&252
\end{bmatrix}
(cA)B=
\begin{bmatrix}
12&21&36\\
24&42&72\\
120&174&252
\end{bmatrix}
A(cB)=
\begin{bmatrix}
12&21&36\\
24&42&72\\
120&174&252
\end{bmatrix}
\end{equation*}

*  perkalian identitas

  AI = IA = A

In [ ]:
i = np.array([[1,0,0],[0,1,0],[0,0,1]])
print('AI=\n',a@i)
print('IA=\n',i@a)
print('A=\n',a)

\begin{equation*}
AI=
\begin{bmatrix}
1&0&2\\
2&0&4\\4&6&8
\end{bmatrix}
IA=
\begin{bmatrix}
1&0&2\\
2&0&4\\
4&6&8
\end{bmatrix}
A=
\begin{bmatrix}
1&0&2\\
2&0&4\\
4&6&8
\end{bmatrix}
\end{equation*}

*  tidak berlaku sifat kumutatif

   AB != BA atau AB tidak sama dengan BA

In [ ]:
print('AB=\n',a@b)
print('BA=\n',b@a)

\begin{align*}
AB=
\begin{bmatrix}
4&-7&4\\
8&14&24\\
40&58&84
\end{bmatrix}
&&
BA=
\begin{bmatrix}
24&24&48\\
38&36&76\\
21&24&76
\end{bmatrix}
\end{align*}



##4. Transpose Matriks


Transpose matriks adalah operasi yang menghasilkan matriks baru dengan menukar baris dan kolom dari matriks asalnya. Dengan kata lain, jika matriks asalnya memiliki dimensi \(mxn), maka transpose-nya akan memiliki dimensi \(nxm), di mana elemen-elemennya dipertukarkan antara baris dan kolom sesuai dengan posisi aslinya.

In [ ]:
c=np.array([[2, 3],[4, 5],[6, 7]])
c_tran = c.transpose()
print('matrik c sebelum di transpose=\n', c)
print('matrik c setelah di transpose=\n',c_tran)
print('ordo C_transpose adalah',c_tran.shape)
z=c_tran@c
print('Z = C_transpose x C =\n',z)
print('ordo z adalah',z.shape)
p=c@c_tran
print('P = C_transpose x C =\n',p)
print('ordo P adalah',p.shape)
print("Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose")

matrik c sebelum di transpose=
 [[2 3]
 [4 5]
 [6 7]]
matrik c setelah di transpose=
 [[2 4 6]
 [3 5 7]]
ordo C_transpose adalah (2, 3)
Z = C_transpose x C =
 [[56 68]
 [68 83]]
ordo z adalah (2, 2)
P = C_transpose x C =
 [[13 23 33]
 [23 41 59]
 [33 59 85]]
ordo P adalah (3, 3)
Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose


##Program Untuk Mengalikan Matriks

In [ ]:
def input_matrix():
    baris = int(input("Masukkan jumlah baris: "))
    kolom = int(input("Masukkan jumlah kolom: "))
    matrix = []
    for i in range(baris):
        row = []
        print(f"Masukkan elemen untuk baris {i + 1}: ")
        for j in range(kolom):
            element = float(input(f"Elemen [{i + 1}, {j + 1}]: "))
            row.append(element)
        matrix.append(row)
    return matrix

def perkalian(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        print("Perkalian matriks tidak dapat dilakukan karena jumlah kolom dalam matriks pertama tidak sama dengan jumlah baris dalam matriks kedua")
        return None
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

def tampilan_hasil(matrix):
    for baris in matrix:
        print(baris)
coba = input("Ingin mengisi matriks sendiri? (iya/tidak) : ")
if coba == "iya":
    print("Program perkalian matriks!!")
    print("Masukkan matriks pertama:")
    matriks1 = input_matrix()
    print ("Matriks 1 = ", matriks1)
    print("Masukkan matriks kedua:")
    matriks2 = input_matrix()
    print ("Matriks 2 = ",matriks2)
elif coba == "tidak":
    print ("Berikut adalah contoh matriks")
    print ("""
    matriks 1=([[1, 0, 2],[2, 0, 4],[4, 6, 8]])
    matriks 224=([[2, 3, 4],[4, 5, 6], [1, 2, 4]])
    """)
    matriks1=([[1, 0, 2],[2, 0, 4],[4, 6, 8]])
    matriks2=([[2, 3, 4],[4, 5, 6], [1, 2, 4]])
else:
    print("Maaf pilihan ersebut tidak tersedia. Tolong masukkan pilihan yang sesuai")

test = perkalian(matriks1, matriks2)
print("\nHasil perkalian matriks:")
tampilan_hasil(test)


Ingin mengisi matriks sendiri? (iya/tidak) : iya
Program perkalian matriks!!
Masukkan matriks pertama:
Masukkan jumlah baris: 2
Masukkan jumlah kolom: 2
Masukkan elemen untuk baris 1: 
Elemen [1, 1]: 3
Elemen [1, 2]: 2
Masukkan elemen untuk baris 2: 
Elemen [2, 1]: 4
Elemen [2, 2]: 2
Matriks 1 =  [[3.0, 2.0], [4.0, 2.0]]
Masukkan matriks kedua:
Masukkan jumlah baris: 2
Masukkan jumlah kolom: 2
Masukkan elemen untuk baris 1: 
Elemen [1, 1]: 3
Elemen [1, 2]: 1
Masukkan elemen untuk baris 2: 
Elemen [2, 1]: 4
Elemen [2, 2]: 2
Matriks 2 =  [[3.0, 1.0], [4.0, 2.0]]

Hasil perkalian matriks:
[17.0, 7.0]
[20.0, 8.0]
