#   Determinant


# sifat-sifat Determinant


1. **Sifat Kali**: Determinan dari hasil perkalian dua matriks sama dengan hasil kali determinan masing-masing matriks.
2. **Sifat Transpose**: Determinan matriks dan transposenya sama.
3. **Perkalian dengan Skalar**: Mengalikan matriks dengan skalar \( k \) mengalikan determinannya dengan \( k^n \).
4. **Determinan Matriks Identitas**: Determinan dari matriks identitas selalu 1.
5. **Penambahan Baris atau Kolom**: Menambahkan kelipatan skalar dari satu baris (atau kolom) ke baris (atau kolom) lainnya tidak mengubah determinan.
6. **Pertukaran Baris atau Kolom**: Menukar dua baris atau kolom pada matriks mengubah tanda determinan.



In [ ]:
import numpy as np


#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)

print("Membuktikan bahwa determinan dari matriks identitas adalah 1")
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
print('Matriks A =\n', I)
print("determinan dari matriks i adalah",det(I))

print("perubahan baris pada matriks identitas untuk mencari determinannya")
I2=np.array([[1,0,0],[0,0,1],[0,1,0]])
print("determinan dari matriks i setelah diubah pertama kali adalah",det(I2))
I3=np.array([[0,1,0],[0,0,1],[1,0,0]])
print("determinan dari matriks i setelah diubah kedua kali adalah",det(I3),"\n")

print("mencari determinan c")
c = np.array([[1,2,1],[3,1,2],[2,1,2]])
print("determinan dari matriks c adalah",det(c))
d = np.array([[3,1,2],[1,2,1],[2,1,2]])
print("determinan dari matriks c setelah diubah pertama kali adalah",det(d))
e = np.array([[1,2,1],[2,4,2],[2,1,2]])
print("determinan dari matriks e adalah",det(e))
print("jika baris dikalikan dengan kelipatan maka hasilnya akan 0")
f = np.array([[1,2,1],[2,4,2],[2,4,3]])
print("determinan dari matriks f adalah",det(f))
g = np.array([[6,2,4],[2,4,2],[4,2,4]])
print("determinan dari matriks g adalah",det(g))#2^3(3)
a=np.array([[3,4],[2,1]])
print("determinan dari matriks a adalah",det(a))
h=np.array([[6,8],[4,2]])
print("determinan dari matriks h adalah",det(h)) #2^2(-5)=-20
i=np.array([[6,8],[2,1]])
print("determinan dari matriks i adalah",det(i)) #jika hanya satu baris saja c det(a) = 2(-5) = -10

print("\nmengalikan salah satu kolom ")
j=np.array([[6,4],[4,1]])
print("determinan dari matriks j adalah",det(j))#hasilnya bakal sama dengan yang salah satu baris saja yang dikalikan

#penumlahan dari determinan A dan (hasil dari A1 dan A2)
g = np.array([[4,1],[2,1]])
print("determinan dari matriks g adalah",det(g))
g = np.array([[7,5],[2,1]])
print("determinan dari matriks g adalah",det(g))

Membuktikan bahwa determinan dari matriks identitas adalah 1
Matriks A =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
determinan dari matriks i adalah 1.0
perubahan baris pada matriks identitas untuk mencari determinannya
determinan dari matriks i setelah diubah pertama kali adalah -1.0
determinan dari matriks i setelah diubah kedua kali adalah 1.0 

mencari determinan c
determinan dari matriks c adalah -3.000000000000001
determinan dari matriks c setelah diubah pertama kali adalah 3.000000000000001
determinan dari matriks e adalah 0.0
jika baris dikalikan dengan kelipatan maka hasilnya akan 0
determinan dari matriks f adalah 0.0
determinan dari matriks g adalah 24.000000000000014
determinan dari matriks a adalah -5.000000000000001
determinan dari matriks h adalah -19.999999999999996
determinan dari matriks i adalah -9.999999999999998

mengalikan salah satu kolom 
determinan dari matriks j adalah -9.999999999999998
determinan dari matriks g adalah 2.0
determinan dari matriks g adalah -2.99999999999999

#  determinant segitiga atas

In [ ]:
import numpy as np

#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)
a= np.array([[1,3,2],[0,2,2],[0,8,9]])
print("determinan dari matriks a adalah",det(a))

determinan dari matriks a adalah 1.9999999999999998


jika dibulatkan:


In [ ]:
import numpy as np

#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)
a= np.array([[1,3,2],[0,2,2],[0,8,9]])
print("determinan dari matriks a adalah",det(a).round())

determinan dari matriks a adalah 2.0


In [ ]:
import numpy as np

#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)
a= np.array([[2,1],[1,1]])
print("determinan dari matriks a adalah",det(a))

b= np.array([[1,1],[1,1]])
print("determinan dari matriks b adalah",det(b))

c= np.array([[3,3],[2,2]])
print("determinan dari matriks c adalah",det(c))





determinan dari matriks a adalah 1.0
determinan dari matriks b adalah 0.0
determinan dari matriks c adalah 0.0


In [ ]:
import numpy as np
import numpy as sy
c=np.array([[2,1],[1,1]])
ab=np.array([[1,1],[1,1]])
print('AB=\n',a@b)

AB=
 [[3 3]
 [2 2]]


#  Kofaktor Matriks


#   Menghitung Kofaktor, Determinan dan Invers suatu matriks

In [ ]:
import numpy as np

# Menghitung kofaktor suatu elemen dalam matriks
def cofactor(matrix, i, j):
    return (-1) ** (i + j) * np.linalg.det(np.delete(np.delete(matrix, i, axis=0), j, axis=1))

# Menghitung matriks kofaktor dari matriks input
def cofactor_matrix(matrix):
    return np.array([[cofactor(matrix, i, j) for j in range(matrix.shape[1])] for i in range(matrix.shape[0])])

# Menghitung determinan matriks
def determinant(matrix):
    return np.linalg.det(matrix)

# Contoh matriks
A = np.array([[3,1,3],
              [2,1,2],
              [4,2,1]])

# Menghitung matriks kofaktor
C = cofactor_matrix(A)
print("Matriks Kofaktor:")
print(C)

# Menghitung determinan
det_A = determinant(A)
print("\nDeterminan:", det_A.round())

# Menghitung invers matriks
def inverse(matrix):
    det = determinant(matrix)
    if det == 0:
        raise ValueError("Determinan nol, matriks tidak dapat diinvers")
    else:
        return cofactor_matrix(matrix).T / det

# Menghitung invers dari matriks A
A_inv = inverse(A)
print("\nInvers Matriks A:")
print(A_inv.round(2))




Matriks Kofaktor:
[[-3.  6.  0.]
 [ 5. -9. -2.]
 [-1. -0.  1.]]

Determinan: -3.0

Invers Matriks A:
[[ 1.   -1.67  0.33]
 [-2.    3.    0.  ]
 [-0.    0.67 -0.33]]


#  Mengitung determinan dari submatriks A21, A22 dan A23

In [ ]:
import numpy as np

# Matriks 3x3
A = np.array([[3, 1, 3],
              [2, 1, 2],
              [4, 2, 1]])

# Membuat submatriks A21, A22, dan A23
A21 = np.delete(np.delete(A, 0, axis=0), 1, axis=1)
A22 = np.delete(np.delete(A, 0, axis=0), 1, axis=1)
A23 = np.delete(np.delete(A, 0, axis=0), 2, axis=1)

# Menghitung determinan dari setiap submatriks
det_A21 = np.linalg.det(A21)
det_A22 = np.linalg.det(A22)
det_A23 = np.linalg.det(A23)

print("Determinan dari submatriks A21:", det_A21.round())

print("Determinan dari submatriks A22:", det_A22.round())

print("Determinan dari submatriks A23:", det_A23.round())



Determinan dari submatriks A21: -6.0
Determinan dari submatriks A22: -6.0
Determinan dari submatriks A23: 0.0


#  Determinan dengan Ekspansi Kolom Kofaktor

In [ ]:
import numpy as np

def minor(matriks, i, j):
    """Menghitung minor dari elemen (i, j) dalam matriks."""
    return np.linalg.det(np.delete(np.delete(matriks, i, axis=0), j, axis=1))

def kofaktor(matriks, i, j):
    """Menghitung kofaktor dari elemen (i, j) dalam matriks."""
    return ((-1) ** (i + j)) * minor(matriks, i, j)

def determinan_dengan_kolom(matriks, kolom):
    """Menghitung determinan matriks menggunakan ekspansi kofaktor pada kolom tertentu."""
    n = len(matriks)
    return sum(matriks[i][kolom] * kofaktor(matriks, i, kolom) for i in range(n))

# Contoh penggunaan:
matriks = np.array([[3, 1, 3],
                    [2, 1, 2],
                    [4, 2, 1]])
det_matriks = determinan_dengan_kolom(matriks, 1)  # Menggunakan kolom kedua (indeks 1)
print(f"Determinan matriks dengan menggunakan kolom kedua adalah: {det_matriks.round()}")

Determinan matriks dengan menggunakan kolom kedua adalah: -3.0


#  Tugas
*  menghitung determinan matrik dan invers matriks
*  bikin dan mebhitung invers matriks 5x5
*  gabungin sama determinan yang kemarin (tugasnya juga)

In [ ]:
import numpy as np

# Membuat matriks 5x5 dengan elemen-elemen yang ditentukan
A = np.array([[5, 0, 3, 3, 5],
              [2, 3, 3, 2, 4],
              [7, 6, 8, 8, 1],
              [6, 7, 7, 4, 1],
              [5, 4, 5, 6, 4]])

print("Matriks A:")
for row in A:
    print(row)

# Menghitung determinan matriks
determinant = np.linalg.det(A)

print("\nDeterminan dari matriks A:", determinant.round())

# Menghitung invers matriks menggunakan numpy
try:
    matrix_inv = np.linalg.inv(A)
    print("\nInvers Matriks A:")
    print(matrix_inv.round(2))
except np.linalg.LinAlgError:
    print("\nDeterminan nol, matriks tidak dapat diinvers")


Matriks A:
[5 0 3 3 5]
[2 3 3 2 4]
[7 6 8 8 1]
[6 7 7 4 1]
[5 4 5 6 4]

Determinan dari matriks A: 423.0

Invers Matriks A:
[[ 0.14 -0.65 -0.46  0.39  0.5 ]
 [-0.23 -0.31 -0.47  0.31  0.64]
 [ 0.19  0.92  0.85 -0.4  -1.27]
 [-0.14 -0.14  0.03 -0.17  0.35]
 [ 0.03  0.19 -0.08 -0.04  0.05]]
