#   Determinant


# sifat-sifat Determinant

1.  hanya dilakukan oleh matriks
2.  determinan dari identitas= 1
3.  jika suatu matriks dikalikan dengan konstanta maka rumus determinanny:
det(kA)=k^n x det A
4.


In [1]:
import numpy as np


#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)

print("Membuktikan bahwa determinan dari matriks identitas adalah 1")
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
print('Matriks A =\n', I)
print("determinan dari matriks i adalah",det(I))

print("perubahan baris pada matriks identitas untuk mencari determinannya")
I2=np.array([[1,0,0],[0,0,1],[0,1,0]])
print("determinan dari matriks i setelah diubah pertama kali adalah",det(I2))
I3=np.array([[0,1,0],[0,0,1],[1,0,0]])
print("determinan dari matriks i setelah diubah kedua kali adalah",det(I3),"\n")

print("mencari determinan c")
c = np.array([[1,2,1],[3,1,2],[2,1,2]])
print("determinan dari matriks c adalah",det(c))
d = np.array([[3,1,2],[1,2,1],[2,1,2]])
print("determinan dari matriks c setelah diubah pertama kali adalah",det(d))
e = np.array([[1,2,1],[2,4,2],[2,1,2]])
print("determinan dari matriks e adalah",det(e))
print("jika baris dikalikan dengan kelipatan maka hasilnya akan 0")
f = np.array([[1,2,1],[2,4,2],[2,4,3]])
print("determinan dari matriks f adalah",det(f))
g = np.array([[6,2,4],[2,4,2],[4,2,4]])
print("determinan dari matriks g adalah",det(g))#2^3(3)
a=np.array([[3,4],[2,1]])
print("determinan dari matriks a adalah",det(a))
h=np.array([[6,8],[4,2]])
print("determinan dari matriks h adalah",det(h)) #2^2(-5)=-20
i=np.array([[6,8],[2,1]])
print("determinan dari matriks i adalah",det(i)) #jika hanya satu baris saja c det(a) = 2(-5) = -10

print("\nmengalikan salah satu kolom ")
j=np.array([[6,4],[4,1]])
print("determinan dari matriks j adalah",det(j))#hasilnya bakal sama dengan yang salah satu baris saja yang dikalikan

#penumlahan dari determinan A dan (hasil dari A1 dan A2)
g = np.array([[4,1],[2,1]])
print("determinan dari matriks g adalah",det(g))
g = np.array([[7,5],[2,1]])
print("determinan dari matriks g adalah",det(g))

Membuktikan bahwa determinan dari matriks identitas adalah 1
Matriks A =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
determinan dari matriks i adalah 1.0
perubahan baris pada matriks identitas untuk mencari determinannya
determinan dari matriks i setelah diubah pertama kali adalah -1.0
determinan dari matriks i setelah diubah kedua kali adalah 1.0 

mencari determinan c
determinan dari matriks c adalah -3.000000000000001
determinan dari matriks c setelah diubah pertama kali adalah 3.000000000000001
determinan dari matriks e adalah 0.0
jika baris dikalikan dengan kelipatan maka hasilnya akan 0
determinan dari matriks f adalah 0.0
determinan dari matriks g adalah 24.000000000000014
determinan dari matriks a adalah -5.000000000000001
determinan dari matriks h adalah -19.999999999999996
determinan dari matriks i adalah -9.999999999999998

mengalikan salah satu kolom 
determinan dari matriks j adalah -9.999999999999998
determinan dari matriks g adalah 2.0
determinan dari matriks g adalah -2.99999999999999

#  determinant segitiga atas

In [2]:
import numpy as np

#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)
a= np.array([[1,3,2],[0,2,2],[0,8,9]])
print("determinan dari matriks a adalah",det(a))

determinan dari matriks a adalah 1.9999999999999998


jika dibulatkan:


In [3]:
import numpy as np

#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)
a= np.array([[1,3,2],[0,2,2],[0,8,9]])
print("determinan dari matriks a adalah",det(a).round())

determinan dari matriks a adalah 2.0


In [4]:
import numpy as np

#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)
a= np.array([[2,1],[1,1]])
print("determinan dari matriks a adalah",det(a))

b= np.array([[1,1],[1,1]])
print("determinan dari matriks b adalah",det(b))

c= np.array([[3,3],[2,2]])
print("determinan dari matriks c adalah",det(c))





determinan dari matriks a adalah 1.0
determinan dari matriks b adalah 0.0
determinan dari matriks c adalah 0.0


In [5]:
import numpy as np
import numpy as sy
c=np.array([[2,1],[1,1]])
ab=np.array([[1,1],[1,1]])
print('AB=\n',a@b)

AB=
 [[3 3]
 [2 2]]
