# Eigenvalue  & Eigenvector
Eigenvalue dan eigenvector adalah konsep penting dalam aljabar linear yang memiliki banyak aplikasi dalam berbagai bidang, termasuk fisika, statistik, dan pembelajaran mesin.
*  Eigenvalue
Eigenvalue adalah suatu nilai skalar
𝜆yang memenuhi persamaan: 𝐴𝑣=𝜆𝑣
*  Eigenvector adalah suatu vektor bukan nol
𝑣 yang, ketika dikalikan dengan matriks
𝐴 menghasilkan suatu vektor yang merupakan skalar kali dari
𝑣 itu sendiri. Dengan kata lain,
𝑣 tidak berubah arah dalam transformasi yang diberikan oleh matriks
𝐴 hanya skala (panjang) nya saja yang berubah.




In [ ]:
import numpy as np

# Membuat matriks 2x2
A = np.array([[1, 4], [2, 3]])

# Menghitung eigenvalues dan eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Menampilkan hasil
print("Matriks A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues.round())
print("\nEigenvectors:")
print(eigenvectors.round())


Matriks A:
[[1 4]
 [2 3]]

Eigenvalues:
[-1.  5.]

Eigenvectors:
[[-1. -1.]
 [ 0. -1.]]


In [6]:
import numpy as np
A = np.array([[1, 4, 5], [2, 3, 4], [1,2,3]])
print(A)

[[1 4 5]
 [2 3 4]
 [1 2 3]]


In [7]:
def det(matriks):
    return np.linalg.det(matriks)

print("Membuktikan bahwa determinan dari matriks identitas adalah 1")
I=np.array([[1, 4, 5], [2, 3, 4], [1,2,3]])
print('Matriks A =\n', I)
print("determinan dari matriks i adalah",det(I))

Membuktikan bahwa determinan dari matriks identitas adalah 1
Matriks A =
 [[1 4 5]
 [2 3 4]
 [1 2 3]]
determinan dari matriks i adalah -1.9999999999999998
