##tidak mengerjakan, tidak boleh masuk kelas!

#aljabar matriks


1.  penjelasan tentang matrik
2.  operasi matrik
3.  buat program u/ mengalikan matrik A dan B
* a dan c = mxn
2. penjumlahan perkalian, penguragan transpose matrik
3. tugas: buat program untuk mengalikan matrik A dan B






  

In [ ]:
import numpy as np
import sympy as sy

In [7]:
#A dan B= 3X3
#C = 3X2
#D = 3x3
import numpy as np
import sympy as sy
A = np.array ([[1, 0, 2],[2, 0, 4],[4, 6, 8]])
B = np.array ([[2, 3, 4],[4, 5, 6], [1, 2, 4]])
C = np.array ([[2, 3],[4, 5],[6, 7]])
D = np.array ([[1, 0, 3],[2, 2, 4],[4, 6, 1]])
print(A)
print(B)
print(C)
print (D)


[[1 0 2]
 [2 0 4]
 [4 6 8]]
[[2 3 4]
 [4 5 6]
 [1 2 4]]
[[2 3]
 [4 5]
 [6 7]]
[[1 0 3]
 [2 2 4]
 [4 6 1]]


In [6]:
import numpy as np
import sympy as sy
A = np.array ([[1, 0, 2],[2, 0, 4],[4, 6, 8]])
B = np.array ([[2, 3, 4],[4, 5, 6], [1, 2, 4]])
C = np.array ([[2, 3],[4, 5],[6, 7]])
D = np.array ([[1, 0, 3],[2, 2, 4],[4, 6, 1]])
print(f"E adalah A+B= \n {A+B}")
print(f"F adalah 2*A= \n {2*A}")
print(f"G adalah A@C= \n {A@C}")
G = A@C
print(G.shape)

E adalah A+B= 
 [[ 3  3  6]
 [ 6  5 10]
 [ 5  8 12]]
F adalah 2*A= 
 [[ 2  0  4]
 [ 4  0  8]
 [ 8 12 16]]
G adalah A@C= 
 [[14 17]
 [28 34]
 [80 98]]
(3, 2)


In [11]:
import numpy as np
import sympy as sy
A = np.array ([[1, 0, 2],[2, 0, 4],[4, 6, 8]])
B = np.array ([[2, 3, 4],[4, 5, 6], [1, 2, 4]])
C = np.array ([[2, 3],[4, 5],[6, 7]])
D = np.array ([[1, 0, 3],[2, 2, 4],[4, 6, 1]])
print(f"A adalah A@(B@C) = \n {(A@B)@C}")





A adalah A@(B@C) = 
 [[108 131]
 [216 262]
 [816 998]]


In [12]:
import numpy as np
import sympy as sy
A = np.array ([[1, 0, 2],[2, 0, 4],[4, 6, 8]])
B = np.array ([[2, 3, 4],[4, 5, 6], [1, 2, 4]])
C = np.array ([[2, 3],[4, 5],[6, 7]])
D = np.array ([[1, 0, 3],[2, 2, 4],[4, 6, 1]])

C_trans = C.transpose()
print (C_trans)
print('\n')
print(C_trans)

[[2 4 6]
 [3 5 7]]


[[2 4 6]
 [3 5 7]]


In [15]:
C_trans= C.transpose()
Cova= C_trans@C
Cova.shape

(2, 2)

In [16]:
C_trans= C.transpose()
Cova= C_trans@C
Cova.shape
Cova

array([[56, 68],
       [68, 83]])

In [17]:
covb=C@C_trans
covb

array([[13, 23, 33],
       [23, 41, 59],
       [33, 59, 85]])